- hosts: web
  become: True
  tasks:
  - name: install apache 2
    yum:
     name: httpd
     state: present
  - name: copying html file
    copy:
     src: index.html
     dest: /var/www/html
  - name: start Httpd
    service:
     name: httpd
     state: started


